# Dockerfile for the addressables builds
FROM nginx:alpine as production-build

ADD ./docker_assets/nginx.conf /etc/nginx/nginx.conf

## Remove default nginx index page
RUN rm -rf /usr/share/nginx/html/*

ARG platform=WebGL
ADD ServerData/$platform /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
